#!/usr/bin/env python

# This file is part of Switchprint.
#
# Switchprint is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Switchprint is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Switchprint.  If not, see <http://www.gnu.org/licenses/>.


import os, sys
import gobject
from dbus.mainloop.glib import DBusGMainLoop


try:
    from switchprint import switch
except ImportError:
    sys.path.append(os.path.abspath(os.path.join(sys.argv[0],"..","..")))
    from switchprint import switch


if __name__ == "__main__":
    # TODO: daemonize this
    main_loop = gobject.MainLoop()
    DBusGMainLoop(set_as_default=True)
    switchboard = switch.SwitchBoard()
    main_loop.run()
