

# This file is part of Switchprint.
#
# Switchprint is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Switchprint is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Switchprint.  If not, see <http://www.gnu.org/licenses/>.


import sys
import dbus
from switchprint._workers.common import list_printers

def on_disconnect(bus_type, handler, *event_args):
    """Worker subprocess to handle on_disconnect events generated by
    hardware monitors."""

    if bus_type == "session":
        bus = dbus.SessionBus()
    elif bus_type == "system":
        bus = dbus.SystemBus()

    for name in list_printers(bus):
        path = "/org/voxelpress/hardware/"+name.split(".")[-1]    
        prox = bus.get_object(name, path)
        if prox.verify_disconnect(event_args[0]):
            break


if __name__ == "__main__":
    on_disconnect(*sys.argv[1:])
